= tikzin(1)
:doctype: manpage
:man manual: Tikzin Manual
:man source: Tikzin 0.1.0
:page-layout: base

== NAME

tikzin - Renders TikZ diagrams to SVG.

== SYNOPSIS

*asciit* [_OPTION_]... _INPUT_PATH_

== DESCRIPTION

The tikzin(1) fish function renders TikZ diagrams to SVG.

== OPTIONS

*-o, --output*=_OUTPUT_PATH_::
  Write output to file _OUTPUT_PATH_.
  Defaults to the base name of the input file suffixed with _.svg_ extension.
  The file is resolved relative to the working directory.

*-p, --package*=+_PACKAGE_::
  Include _\usepackage{PACKAGE}_ when rendering the diagram.

*-q, --quiet*::
  Silence application log messages and script warnings.

*-h, --help*::
  Print a help message.

== ENVIRONMENT

*Tikzin* requires _texlive_ and _pdf2svg_ to be installed. Make sure any 
additional LaTeX packages are installed before using them in a diagram.

== EXIT STATUS

*0*::
  Success.

*1*::
  Failure (syntax or usage error; configuration error).

*n*::
  Failure (document processing failure).

== AUTHORS

*Tikzin* was written by Pablo Emílio Escobar Gavira <pablo-escobar@riseup.net>.

*TeX Live* has been developed since 1996 by collaboration between the TeX user 
groups. TeX Live was originally perpetrated by Sebastian Rahtz. Present 
miscreants include Akira Kakuto, Karl Berry, Luigi Scarso, Mojca Miklavec, 
Norbert Preining, Reinhard Kotucha, Siep Kroonenberg, and a cast of thousands.

*pdf2svg* was written by David Barton <davebarton@cityinthesky.co.uk> and 
Matthew Flaschen <matthew.flaschen@gatech.edu>.

== RESOURCES

*Git source repository on GitHub:* https://github.com/GarkGarcia/tikzin

== COPYING

Copyright \(C) 2020 Pablo Emílio Escobar Gaviria
Free use of this software is granted under the terms of the GPL-3.0 License.

