= tikztosvg(1)
Pablo Emílio Escobar Gaviria <pablo-escobar@riseup.net>
:imagesdir: example

image:https://img.shields.io/github/v/release/GarkGarcia/tikztosvg[link=https://github.com/GarkGarcia/tikztosvg/releases]
image:https://img.shields.io/ctan/v/tikztosvg[link=https://www.ctan.org/pkg/tikztosvg]
image:https://img.shields.io/github/license/GarkGarcia/tikztosvg[link=https://github.com/GarkGarcia/tikztosvg/blob/master/LICENSE]

The `tikztosvg(1)` command renders TikZ diagrams to SVG, using 
http://xetex.sourceforge.net/[`xetex`] and 
https://github.com/dawbarton/pdf2svg[`pdf2svg`].

== Usage

----
tikztosvg [OPTION]... INPUT_PATH
----

If `INPUT_PATH` is set to `-` the input will be read from stdin.

=== Options

*-o, --output*=_OUTPUT_PATH_::
  Write output to file _OUTPUT_PATH_.
  If set to `-` the output will be written to stdout.
  Defaults to the base name of the input file suffixed with the _.svg_ 
  extension. The file is resolved relative to the working directory.

*-p, --package*=+_PACKAGE_::
  Include ``\usepackage{_PACKAGE_}`` when rendering the diagram.

*-q, --quiet*::
  Silence application log messages and script warnings.

*-h, --help*::
  Print a help message.

*-v, --version*::
  Print version information.

== Example

Let's say you want to convert the file `exemple.tikz` to SVG:

[source, latex]
----
\begin{tikzcd}
    G \arrow[r, "\varphi"] \arrow[d, "\psi"', two heads] & H \\
    \sfrac{G}{\ker \varphi} \arrow[ru, dotted]           &  
\end{tikzcd}
----

You could achieve that by running the following command:

----
tikztosvg -p tikz-cd -p xfrac example.tikz
----

The results will be stored in the file `example.svg`:

image::example.svg[]

== Installation

The `tikztosvg(1)` command and it's man page can be installed in Unix systems by 
running:

----
$ curl -s https://raw.githubusercontent.com/GarkGarcia/tikztosvg/master/install.sh | sudo sh
----

The executable is installed in `$HOME/.local/bin/` and the man-page is 
installed in `$HOME/.local/share/man/man1/`.

== Authors

*TikzToSvg* was written by 
mailto:pablo-escobar@riseup.net[Pablo Emílio Escobar Gavira].

*pdf2svg* was written by mailto:davebarton@cityinthesky.co.uk[David Barton] and 
mailto:matthew.flaschen@gatech.edu[Matthew Flaschen].

== License

(C) 2020 Pablo Emílio Escobar Gaviria.

Free use of this software is granted under the terms of the GPL-3.0 License.

