= tikzin(1)
Pablo Emílio Escobar Gaviria <pablo-escobar@riseup.net>
:imagesdir: example

The `tikzin(1)` command renders TikZ diagrams to SVG, using 
https://fishshell.com/[`fish`], https://tug.org/texlive/[`texlive`] and 
https://github.com/dawbarton/pdf2svg[`pdf2svg`].

== Usage

----
tikzin [OPTION]... INPUT_PATH
----

=== Options

*-o, --output*=_OUTPUT_PATH_::
  Write output to file _OUTPUT_PATH_.
  Defaults to the base name of the input file suffixed with _.svg_ extension.
  The file is resolved relative to the working directory.

*-p, --package*=+_PACKAGE_::
  Include ``\usepackage{_PACKAGE_}`` when rendering the diagram.

*-q, --quiet*::
  Silence application log messages and script warnings.

*-h, --help*::
  Print a help message.

== Example

Let's say you want to convert the file `exemple.tikz` to SVG:

[source, latex]
----
\begin{tikzcd}
    G \arrow[r, "\varphi"] \arrow[d, "\psi"', two heads] & H \\
    \sfrac{G}{\ker \varphi} \arrow[ru, dotted]           &  
\end{tikzcd}
----

You could achieve that by runned the following command:

----
tikzit -p tikz-cd -p xfrac example.tikz
----

The results will be stored in the file `example.svg`:

image::example.svg[]

== Authors

*Tikzin* was written by 
mailto:pablo-escobar@riseup.net[Pablo Emílio Escobar Gavira].

*TeX Live* has been developed since 1996 by collaboration between the TeX user 
groups. TeX Live was originally perpetrated by Sebastian Rahtz. Present 
miscreants include Akira Kakuto, Karl Berry, Luigi Scarso, Mojca Miklavec, 
Norbert Preining, Reinhard Kotucha, Siep Kroonenberg, and a cast of thousands.

*pdf2svg* was written by mailto:davebarton@cityinthesky.co.uk[David Barton] and 
mailto:matthew.flaschen@gatech.edu[Matthew Flaschen].

== License

(C) 2020 Pablo Emílio Escobar Gaviria.

Free use of this software is granted under the terms of the GPL-3.0 License.

